### ISSUE TITLE
dual monitors

### ISSUE THREAD

**Issue by R0flcopt3r** [TomJamesGray/fortune-i3lock#2]
I'm having an issue that when using dual monitors, the icon and quote is localed in the middle of the two monitors.

I have zero experience with imageMagick, but I've tried different -gravity settings, -page and -region. If you have any tips, that would be great.

Resolution is 6880x1440 in total, 3440x1440 on both screens.

**Comment by TomJamesGray** [comment]
Hi, I too use dual monitors next to each other landscape so I did have to modify [the script](https://gist.github.com/TomJamesGray/09ccdeaa6b94ddad1f39e235839f08a6) it a bit too to get it to work well on my monitors, 1920_1080 on the left and 1600_900 on the right.

The main differences are:
- The addition of the geometry flag on the icon, in your case that should probably read (assuming you're using the same lock icon 256px \* 256px) `-geometry +1592-592` 
  - `(3440/2)-(256/2) = 1592`
  - `(1440/2)-(256/2) = 592`
  - The geometry on the text (line 17) which in your case should probably be `+0-868` if you want to have a 20px gap between the bottom of the icon and the text
    - `592+256+20 = 848`

Feel free to comment if you need more help as I may have messed something up in my calculations or not explained it that well

**Comment by R0flcopt3r** [comment]
Awesome! I tried this at home, and it works great! I'll give it a go when I
return to work on Monday, thank you very much for your help!

2016-07-29 21:39 GMT+02:00 Tom Gray notifications@github.com:
